version: "3.8"
services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend/app:/app/app   # live reload
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/app          # live reload
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
